import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container:{
        flex:1
    },
    navbar:{
        borderBottomWidth:1,
        borderBottomColor:"#CCC"
    },
    avatar:{
        width:70,
        height:70,
        borderRadius:40,
    },
    header:{
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        padding:10,
        borderBottomWidth:1,
        borderBottomColor:"#CCC"
    },
    header__title:{
        fontSize:20,
        fontWeight:"500"
    },
    header__image:{
        width:30,
        height:30
    },
    body:{
        padding:10,
        borderBottomWidth:1,
        borderBottomColor:"#CCC"
    },
    body__title:{
        flexDirection:"row",
        margin:10
    },
    body__title__text:{
        flexDirection:"row",
        justifyContent:"space-between",
        marginLeft:10
    }, 
    other_avatar:{
        width:30,
        height:30,
    },
    body__title__text_more:{
        textAlign: 'right',
    },
    textContent:{
        fontSize:15,
        fontWeight:"bold",
    },
    textHeaderDesc:{
        fontSize:15,
    }
})